## 예외 계층

![Untitled](https://user-images.githubusercontent.com/106054507/190154134-76e2b5cd-adac-4519-afc2-aa5b35425a8d.png)


- `Object` : 예외도 객체이다. 모든 객체의 최상위 부모는 `Object` 이므로 예외의 최상위 부모도 Object 이다.
- `Throwable` : 최상위 예외이다. 하위에 `Exception` 과 `Error` 가 있다.
- `Error` : 메모리 부족이나 심각한 시스템 오류와 같이 애플리케이션에서 복구 불가능한 시스템 예외이다. 애플리케이션 개발자는 이 예외를 잡으려고 해서는 안된다.
    - 상위 예외를 `catch` 로 잡으면 그 하위 예외까지 함께 잡는다. 따라서 애플리케이션 로직에서는 `Throwable`예외도 잡으면 안되는데, 앞서 이야기한 `Error` 예외도 함께 잡을 수 있기 때문에다. 애플리케이션 로직은 이런 이유로 `Exception` 부터 필요한 예외로 생각하고 잡으면 된다.
    - `Error` 도 언체크 예외이다.
- `Exception` : 체크 예외
    - 애플리케이션 로직에서 사용할 수 있는 실질적인 최상위 예외이다.
    - `Exception` 과 그 하위 예외는 모두 컴파일러가 체크하는 체크 예외이다. 단 `RuntimeException` 은 예외로 한다.
- `RuntimeException` : 언체크 예외, 런타임 예외
    - 컴파일러가 체크 하지 않는 언체크 예외이다.
    - `RuntimeException` 과 그 자식 예외는 모두 언체크 예외이다.
    - `RuntimeException` 의 이름을 따라서 `RuntimeException` 과 그 하위 언체크 예외를 런타임
    예외라고 많이 부른다. 여기서도 앞으로는 런타임 예외로 종종 부르겠다.
    

## 예외 기본 규칙

- **예외에  2가지 기본 규칙**
    - 예외는 잡아서 처리하거나 던져야 한다.
    - 예외를 잡거나 던질 때 지정한 예외뿐만 아니라 그 예외의 자식들도 함께 처리된다
    
- **예외를 처리하지 못할 경우?**
    - 자바 `main()` 쓰레드의 경우 예외 로그를 출력하면서 시스템이 종료된다.
    - 웹 애플리케이션의 경우 WAS가 해당 예외를 받아서 처리하는데, 주로 사용자에게 개발자가 지정한, 오류 페이지를 보여준다

- **체크 예외 VS 언체크 예외**
    - 체크 예외: 예외를 잡아서 처리하지 않으면 항상 `throws` 에 던지는 예외를 선언해야 한다.
    - 언체크 예외: 예외를 잡아서 처리하지 않아도 `throws` 를 생략할 수 있다.

## 체크 예외 기본 이해

- `Exception` 과 그 하위 예외는 모두 컴파일러가 체크하는 체크 예외이다.

```java
@Slf4j
public class CheckedTest {

    @Test
    void checked_catch(){
        Service service = new Service();
        service.callCatch();
    }

    @Test
    void checked_throw(){
        Service service = new Service();
        assertThatThrownBy(() -> service.callThrow())
                .isInstanceOf(MyCheckedException.class);
    }

    static class MyCheckedException extends Exception {
        public MyCheckedException(String message) {
            super(message);
        }
    }

    static class Service{
        Repository repository = new Repository();

        public void callCatch(){
            try {
                repository.call();
            } catch (MyCheckedException e) {
                log.info("예외 처리, message = {}", e.getMessage(), e);
            }
        }

        public void callThrow() throws MyCheckedException{
            repository.call();
        }
    }

    static class Repository{
        public void call() throws MyCheckedException {
            throw new MyCheckedException("ex");
        }
    }
}
```

- **예외 정상 처리 실행 순서**
    1. `test service.callCatch()` → `repository.call() [예외 발생, 던짐]`
    2. `test`  ← `service.callCatch() [예외 처리]` ← `repository.call()`
    3. `test` → `[정상 흐름] service.callCatch()` →  `repository.call()`
- **예외 Throw 실행 순서**
    1. `test service.callThrow()` → `repository.call() [예외 발생, 던짐]`
    2. `test` ← `service.callThrow() [예외 던짐]` ← `repository.call()`
    3. `test` → `[예외 도착] service.callThrow()` → `repository.call()`
    
- **체크 예외의 장단점**
    - 장점: 개발자가 실수로 예외를 누락하지 않도록 컴파일러를 통해 문제를 잡아주는 훌륭한 안전 장치이다.
    - 단점: 하지만 실제로는 개발자가 모든 체크 예외를 반드시 잡거나 던지도록 처리해야 하기 때문에, 너무 번거로운 일이 된다. 크게 신경쓰고 싶지 않은 예외까지 모두 챙겨야 한다.
    

## 언체크 예외 기본 이해

- `RuntimeException` 과 그 하위 예외는 언체크 예외로 분류된다.
- 언체크 예외는 말 그대로 컴파일러가 예외를 체크하지 않는다는 뜻이다.
- 예외를 던지는 `throws` 를 선언하지 않고, 생략할 수 있다. 이 경우 자동으로 예외를 던진다.

```java
@Slf4j
public class UncheckedTest {

    @Test
    void unchecked_catch(){
        Service service = new Service();
        service.callCatch();
    }

    @Test
    void unchecked_throw(){
        Service service = new Service();
        assertThatThrownBy(() -> service.callThrow())
                .isInstanceOf(MyUncheckedException.class);
    }

    static class MyUncheckedException extends RuntimeException{
        public MyUncheckedException(String message) {
            super(message);
        }

    }

    /**
     * Unchecked 예외는
     * 예외를 잡거나, 던지지 않아도 된다.
     * 예외를 잡지 않으면 자동으로 밖으로 던진다.
     */
    static class Service{
        Repository repository = new Repository();

        public void callCatch(){
            try{
                repository.call();
            }catch (MyUncheckedException e){
                log.info("예외 처리, message = {}", e.getMessage(), e);
            }
        }

        public void callThrow(){
            repository.call();
        }
    }

    static class Repository{
        public void call(){
            throw new MyUncheckedException("ex");
        }

    }
}
```

- **언체크 예외의 장단점**
    - 장점: 신경쓰고 싶지 않은 언체크 예외를 무시할 수 있다.
    - 단점: 언체크 예외는 개발자가 실수로 예외를 누락할 수 있다. 반면에 체크 예외는 컴파일러를 통해 예외 누락을 잡아준다
    

## 체크 예외 활용

- **기본 원칙 2가지**
    - 기본적으로 언체크(런타임) 예외를 사용하자.
    - 체크 예외는 비즈니스 로직상 의도적으로 던지는 예외에만 사용하자.
        - **체크 예외 예**
            - 계좌 이체 실패 예외
            - 결제시 포인트 부족 예외
            - 로그인 ID, PW 불일치 예외

- **체크 예외의 문제점**
    - 다른 로직에서 발생한 `Exception`을 이후 로직에서 해당 `Exception` 을 모두 처리해야한다.
    - **2가지 문제**
        - 복구 불가능한 예외
        - 의존 관계에 대한 문제

```java
@Slf4j
public class CheckedAppTest {
    
    @Test
    void checked(){
        Controller controller = new Controller();
        Assertions.assertThatThrownBy(() -> controller.request())
                .isInstanceOf(Exception.class);
    }

    static class Controller{
        Service service = new Service();

        public void request() throws SQLException, ConnectException {
            service.logic();
        }
    }

    static class Service{
        Repository repository = new Repository();
        NetworkClient networkClient = new NetworkClient();

        public void logic() throws SQLException, ConnectException {
            repository.call();
            networkClient.call();
        }
    }

    static class NetworkClient{
        public void call() throws ConnectException {
            throw new ConnectException("연결 실패");
        }
    }

    static class Repository{
        public void call() throws SQLException{
            throw new SQLException("ex");
        }
    }
}
```

## 언체크 예외 활용

- 런타임 예외를 사용하면 중간에 기술이 변경되어도 해당 예외를 사용하지 않는 코드를 변경하지 않아도 된다.
- 변경의 영향 범위는 최소화 된다.

```java
@Slf4j
public class UncheckedAppTest {

    @Test
    void unchecked(){
        Controller controller = new Controller();
        Assertions.assertThatThrownBy(() -> controller.request())
                .isInstanceOf(Exception.class);
    }

    static class Controller{
        Service service = new Service();

        public void request() {
            service.logic();
        }
    }

    static class Service{
        Repository repository = new Repository();
        NetworkClient networkClient = new NetworkClient();

        public void logic() {
            repository.call();
            networkClient.call();
        }
    }

    static class NetworkClient{
        public void call() {
            throw new RuntimeConnectException("연결실패");
        }
    }

    static class Repository{
        public void call(){
            try {
                runSQL();
            } catch (SQLException e) {
                throw new RuntimeSQLException(e);
            }
        }

        public void runSQL() throws SQLException {
            throw new SQLException("ex");
        }
    }

    static class RuntimeConnectException extends RuntimeException{
        public RuntimeConnectException(String message) {
            super(message);
        }
    }

    static class RuntimeSQLException extends RuntimeException{
        public RuntimeSQLException(Throwable cause) {
            super(cause);
        }
    }
}
```

- **런타임 예외 - 대부분 복구 불가능한 예외 해결**
    - 시스템에서 발생한 예외는 대부분 복구 불가능 예외이다. 런타임 예외를 사용하면 서비스나 컨트롤러가 이런 복구 불가능한 예외를 신경쓰지 않아도 된다. 물론 이렇게 복구 불가능한 예외는 일관성 있게 공통으로 처리해야 한다.
    
- **런타임 예외 - 의존 관계에 대한 문제 해결**
    - 런타임 예외는 해당 객체가 처리할 수 없는 예외는 무시하면 된다. 따라서 체크 예외 처럼 예외를 강제로 의존하지 않아도 된다.
    

## 예외 포함과 스택 트레이스

- 예외를 전환할 때는 기존 예외를 포함해야 한다. 그렇지 않으면 스택 트레이스를 확인할 때 심각한 문제가 발생한다

```java
static class Repository{
    public void call(){
        try {
            runSQL();
        } catch (SQLException e) {
            throw new RuntimeSQLException(e);
        }
    }

    public void runSQL() throws SQLException {
         throw new SQLException("ex");
    }
}
```

- 예외를 포함하지 않아서 기존에 발생한 `java.sql.SQLException` 과 스택 트레이스를 확인할 수 없다. 변환한 `RuntimeSQLException` 부터 예외를 확인할 수 있다. 만약 실제 DB에 연동했다면 DB에서 발생한 예외를 확인할 수 없는 심각한 문제가 발생한다
